/**
 * CRACKL — Legacy Styles
 * These are the existing styles from the monolith App.js.
 * Screens that haven't been redesigned yet import from here.
 * As each screen gets redesigned (Phases 2-8), its styles migrate to the new design system.
 */
import { StyleSheet } from 'react-native';

// Legacy color constants (used by un-redesigned screens)
export const C = {
  bg:       '#0d1117',
  surface:  '#161b22',
  card:     '#1c2128',
  cardB:    '#22272e',
  accent:   '#3b82f6',
  accentLt: '#60a5fa',
  accentBg: '#3b82f615',
  gold:     '#f59e0b',
  green:    '#22c55e',
  red:      '#ef4444',
  orange:   '#f97316',
  purple:   '#a855f7',
  purpleBg: '#a855f715',
  blue:     '#3b82f6',
  text:     '#e6edf3',
  sub:      '#8b949e',
  muted:    '#6e7681',
  border:   '#30363d',
  divider:  '#21262d',
};

const S = StyleSheet.create({
  fill:       { flex: 1 },
  center:     { justifyContent: 'center', alignItems: 'center' },
  row:        { flexDirection: 'row', alignItems: 'center' },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  splashTitle:{ color: C.text, fontSize: 54, fontWeight: '900', letterSpacing: 7, marginTop: 18 },
  splashSub:  { color: C.sub,  fontSize: 16, marginTop: 8 },
  chip:       { paddingHorizontal: 14, paddingVertical: 7, borderRadius: 124, borderWidth: 1, borderColor: C.border, backgroundColor: C.card },
  chipT:      { color: C.sub, fontSize: 13 },
  authLeft:   { flex: 1.1, backgroundColor: '#05040a', borderRightWidth: 1, borderColor: '#1f1635', padding: 52, overflow: 'hidden' },
  authRight:  { width: 440, backgroundColor: '#09090e', justifyContent: 'center', alignItems: 'center', padding: 56 },
  authBrand:  { color: '#fff', fontWeight: '900', fontSize: 13, marginLeft: 10, letterSpacing: 1.5 },
  heroWhite:  { color: '#fff', fontSize: 52, fontWeight: '900', lineHeight: 52, alignSelf: 'flex-start' },
  heroBlue:   { color: '#a855f7', fontSize: 52, fontWeight: '900', lineHeight: 54, fontStyle: 'italic', alignSelf: 'flex-start' },
  heroBody:   { color: '#8b949e', fontSize: 13, marginTop: 24, lineHeight: 22, letterSpacing: 1.5, fontWeight: '600', maxWidth: 440, textTransform: 'uppercase' },
  authH:      { color: '#fff', fontSize: 18, fontWeight: '800', marginBottom: 4 },
  authSub:    { color: '#6e7681', fontSize: 12, lineHeight: 18, marginBottom: 28 },
  inputCyber: { backgroundColor: '#09090e', borderWidth: 1, borderColor: '#1f1635', borderRadius: 4, paddingHorizontal: 16, paddingVertical: 14, color: '#fff', fontSize: 13, marginBottom: 16 },
  inputBoxWrapCyber: { flexDirection: 'row', alignItems: 'stretch' },
  eyeBtnCyber:{ width: 46, backgroundColor: '#09090e', borderWidth: 1, borderColor: '#1f1635', borderLeftWidth: 0, borderTopRightRadius: 4, borderBottomRightRadius: 4, alignItems: 'center', justifyContent: 'center' },
  lockIconBox:{ width: 42, backgroundColor: '#09090e', borderWidth: 1, borderColor: '#1f1635', borderRightWidth: 0, borderTopLeftRadius: 4, borderBottomLeftRadius: 4, alignItems: 'center', justifyContent: 'center' },
  checkboxCyber: { width: 16, height: 16, borderRadius: 3, borderWidth: 1, borderColor: '#4b5563', backgroundColor: '#09090e', alignItems: 'center', justifyContent: 'center' },
  checkboxOnCyber: { backgroundColor: '#a855f7', borderColor: '#a855f7' },
  btnPrimaryCyber: { backgroundColor: '#a855f7', paddingVertical: 14, borderRadius: 4, alignItems: 'center', marginTop: 4 },
  btnPrimaryTCyber:{ color: '#fff', fontWeight: '800', fontSize: 12, letterSpacing: 1 },
  orLineCyber:  { flex: 1, height: 1, backgroundColor: '#1f1635' },
  orTCyber:     { color: '#4b5563', fontSize: 9, fontWeight:'700', letterSpacing:1.5, paddingHorizontal: 16 },
  btnOauthCyber: { backgroundColor: '#05040a', borderWidth: 1, borderColor: '#1f1635', paddingVertical: 12, borderRadius: 4, flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
  btnOauthTCyber: { color: '#8b949e', fontWeight: '600', fontSize: 12 },
  errT:       { color: C.red, fontSize: 13, fontWeight: '600', marginBottom: 14, textAlign: 'center' },
  rowCenter:  { flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
  topBar:     { height: 80, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 32, backgroundColor: '#09090e', borderBottomWidth: 1, borderColor: '#1f1635', zIndex: 10 },
  topBrand:   { color: '#fff', fontWeight: '900', fontSize: 13, letterSpacing: 1.5, marginLeft: 10 },
  topUser:    { flexDirection: 'row', alignItems: 'center', gap: 14, paddingLeft: 0 },
  topAvatar:  { width: 44, height: 44, borderRadius: 8, backgroundColor: '#05040a', borderWidth: 1, borderColor: '#1f1635', alignItems: 'center', justifyContent: 'center' },
  topName:    { color: '#fff', fontWeight: '800', fontSize: 14 },
  topRank:    { color: '#8b949e', fontSize: 11, marginTop: 4, letterSpacing: 0.5 },
  statPillContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#05040a', borderRadius: 6, borderWidth: 1, borderColor: '#1f1635', overflow: 'hidden' },
  statPillL:  { paddingHorizontal: 16, paddingVertical: 10, borderRightWidth: 1, borderColor: '#1f1635' },
  statPillLT: { color: C.gold, fontWeight: '800', fontSize: 13 },
  statPillR:  { paddingHorizontal: 16, paddingVertical: 10, backgroundColor: '#22c55e15' },
  statPillRT: { color: C.green, fontWeight: '800', fontSize: 13 },
  iconBtn:    { width: 44, height: 44, borderRadius: 8, backgroundColor: '#05040a', borderWidth: 1, borderColor: '#1f1635', alignItems: 'center', justifyContent: 'center' },
  bigAvatar:  { width: 80, height: 80, borderRadius: 16, backgroundColor: '#05040a', borderWidth: 2, borderColor: '#a855f755', alignItems: 'center', justifyContent: 'center' },
  sidebar:        { width: 240, backgroundColor: '#05040a', paddingVertical: 24, paddingHorizontal: 16, borderRightWidth: 1, borderColor: '#1f1635' },
  sideLabel:      { color: '#4b5563', fontSize: 10, fontWeight: '800', letterSpacing: 2, paddingHorizontal: 12, marginBottom: 16, marginTop: 10 },
  navItem:        { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, paddingHorizontal: 16, borderRadius: 6, marginBottom: 4, position: 'relative' },
  navItemOn:      { backgroundColor: '#09090e', borderWidth: 1, borderColor: '#1f1635' },
  navActiveLine:  { display: 'none' },
  navLabel:       { color: '#8b949e', fontSize: 13, fontWeight: '700', flex: 1, marginLeft: 6 },
  navLabelOn:     { color: '#fff', fontWeight: '800' },
  page:       { padding: 32, paddingBottom: 60, backgroundColor: '#09090e' },
  pageHeader: { padding: 32, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderColor: C.border },
  pageTitle:  { color: C.text, fontSize: 22, fontWeight: '800', marginBottom: 16 },
  secH:       { color: '#fff', fontSize: 16, fontWeight: '800', letterSpacing: 1 },
  card:       { backgroundColor: '#05040a', borderRadius: 8, padding: 20, borderWidth: 1, borderColor: '#1f1635' },
  featCard:       { borderRadius: 16, padding: 36, overflow: 'hidden', borderWidth: 1, borderColor: '#1f1635', backgroundColor: '#05040a', position: 'relative' },
  eventBadge:     { backgroundColor: '#a855f725', borderWidth: 1, borderColor: '#a855f750', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 4 },
  eventBadgeT:    { color: '#a855f7', fontWeight: '800', fontSize: 10, letterSpacing: 1.5 },
  featTitle:      { color: '#fff', fontSize: 40, fontWeight: '900', lineHeight: 48, marginBottom: 16, marginTop: 24, letterSpacing: -1 },
  featDesc:       { color: '#8b949e', fontSize: 14, lineHeight: 22, maxWidth: 400, fontWeight: '500' },
  enterBtn:       { backgroundColor: '#fff', borderWidth: 1, borderColor: '#fff', paddingHorizontal: 24, paddingVertical: 14, borderRadius: 4, marginTop: 28, alignSelf: 'flex-start' },
  enterBtnT:      { color: '#09090e', fontWeight: '800', fontSize: 13, letterSpacing: 1 },
  arenaCard:      { backgroundColor: '#05040a', borderRadius: 8, padding: 24, borderWidth: 1, borderColor: '#1f1635', flexDirection: 'row', alignItems: 'center', gap: 20 },
  arenaIconBox:   { width: 56, height: 56, borderRadius: 8, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#1f1635' },
  arenaTitle:     { color: '#fff', fontSize: 16, fontWeight: '800', marginBottom: 6, letterSpacing: 0.5 },
  arenaDesc:      { color: '#8b949e', fontSize: 13, lineHeight: 20, flexShrink: 1 },
  arenaCTA:       { fontWeight: '800', fontSize: 12, paddingLeft: 12, letterSpacing: 1 },
  quickGrid:  { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 14 },
  qCard:      { width: '47.5%', backgroundColor: '#05040a', borderRadius: 8, padding: 20, borderWidth: 1, borderColor: '#1f1635' },
  qLabel:     { color: '#fff', fontWeight: '800', fontSize: 13, marginTop: 12, letterSpacing: 0.5 },
  qSub:       { color: '#6e7681', fontSize: 11, marginTop: 4, fontWeight: '600' },
  tabRow:     { flexDirection: 'row', backgroundColor: C.card, borderRadius: 10, padding: 3 },
  tab:        { paddingHorizontal: 20, paddingVertical: 9, borderRadius: 8 },
  tabOn:      { backgroundColor: C.accent },
  tabT:       { color: C.sub, fontWeight: '600', fontSize: 14 },
  gameBar:    { height: 64, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 28, backgroundColor: C.surface, borderBottomWidth: 1, borderColor: C.border },
  backPill:   { backgroundColor: C.card, paddingHorizontal: 16, paddingVertical: 9, borderRadius: 120, borderWidth: 1, borderColor: C.border },
  modePill:   { paddingHorizontal: 16, paddingVertical: 7, borderRadius: 120, borderWidth: 1 },
  statPill:   { backgroundColor: C.card, paddingHorizontal: 16, paddingVertical: 9, borderRadius: 120, borderWidth: 1, borderColor: C.border },
  statPillT:  { color: C.gold, fontSize: 14, fontWeight: '800' },
  questionCard: { backgroundColor: C.card, borderRadius: 18, padding: 28, marginBottom: 20, borderWidth: 1, borderColor: C.border },
  questionT:    { color: C.text, fontSize: 20, lineHeight: 34, fontWeight: '500' },
  hintTrigger:  { marginTop: 18, padding: 12, borderRadius: 10, backgroundColor: C.gold+'0e', alignItems: 'center', borderWidth: 1, borderColor: C.gold+'25' },
  hintBox:      { marginTop: 14, padding: 14, borderRadius: 12, backgroundColor: C.gold+'0e', borderWidth: 1, borderColor: C.gold+'28' },
  optRow:     { backgroundColor: C.card, borderRadius: 12, padding: 16, marginBottom: 10, flexDirection: 'row', alignItems: 'center', gap: 14, borderWidth: 1.5, borderColor: C.border },
  optRight:   { backgroundColor: C.green+'12', borderColor: C.green },
  optWrong:   { backgroundColor: C.red+'12',   borderColor: C.red },
  optBadge:   { width: 36, height: 36, borderRadius: 9, backgroundColor: C.border, justifyContent: 'center', alignItems: 'center' },
  optText:    { flex: 1, fontSize: 15, fontWeight: '500', color: C.text },
  typeInput:  { backgroundColor: C.card, borderWidth: 1.5, borderColor: C.accent+'55', borderRadius: 14, padding: 18, color: C.text, fontSize: 16, minHeight: 80, textAlignVertical: 'top' },
  resultCard: { borderRadius: 120, padding: 28, alignItems: 'center', borderWidth: 2, backgroundColor: C.card, marginTop: 10 },
  verdictT:   { fontSize: 28, fontWeight: '900', marginTop: 8 },
  ansReveal:  { marginTop: 16, padding: 18, borderRadius: 14, backgroundColor: C.bg, width: '100%', alignItems: 'center', borderWidth: 1, borderColor: C.border },
  coinsDelta: { marginTop: 14, paddingHorizontal: 28, paddingVertical: 12, borderRadius: 120, backgroundColor: C.bg, borderWidth: 1 },
  miniChip:   { backgroundColor: C.cardB, paddingHorizontal: 14, paddingVertical: 6, borderRadius: 120, borderWidth: 1, borderColor: C.border },
  lvlBanner:  { backgroundColor: C.accent+'18', borderRadius: 12, padding: 14, marginTop: 12, borderWidth: 1, borderColor: C.accent+'45', width: '100%', alignItems: 'center' },
  factBox:    { backgroundColor: C.bg, borderRadius: 14, padding: 16, marginTop: 14, width: '100%', borderWidth: 1, borderColor: C.border },
  tblHead:    { flexDirection:'row', alignItems:'center', backgroundColor:C.cardB, borderRadius:10, paddingVertical:12, paddingHorizontal:16, marginBottom:8 },
  tblH:       { color:C.muted, fontSize:11, fontWeight:'700', letterSpacing:0.8 },
  tblRow:     { flexDirection:'row', alignItems:'center', paddingVertical:14, paddingHorizontal:16, marginBottom:2, borderBottomWidth:1, borderColor:C.divider },
  tblCell:    { color:C.text, fontSize:14 },
  tierRow:    { backgroundColor:C.card, borderRadius:14, padding:20, flexDirection:'row', justifyContent:'space-between', alignItems:'center', borderWidth:1.5, borderColor:C.border },
  badgeCard:  { backgroundColor:C.card, borderRadius:14, padding:18, borderWidth:1, borderColor:C.border, alignItems:'center', width:145 },
  selBtn:     { paddingHorizontal:16, paddingVertical:10, borderRadius:10, borderWidth:1.5, borderColor:C.border, backgroundColor:C.card },
  settingH:   { color:C.text, fontSize:14, fontWeight:'700', marginBottom:10 },
  fldLabel:   { color: C.sub, fontSize: 12, fontWeight: '600', marginBottom: 6, marginTop: 12 },
  btnPrimary: { backgroundColor: C.accent, borderRadius: 12, paddingVertical: 16, alignItems: 'center' },
  btnPrimaryT:{ color: '#fff', fontWeight: '800', fontSize: 15 },
});

export default S;
